
[build]
  command = "npm install"  # Perintah untuk menginstal dependensi
  functions = "functions"  # Menentukan folder "functions"

[functions]
  node_bundler = "esbuild" # Gunakan esbuild. Lebih cepat dari bundler bawaan
  external_node_modules = ["puppeteer"] # WAJIB: Beri tahu Netlify untuk menyertakan Puppeteer.