services:
  - type: web
    name: kuramanime
    image:
      build:
        context: .
        dockerfile: Dockerfile
    env:
      PORT: 3000 # Set the port (Render uses port 10000 by default, but we specify here)
    port: 3000
    autoDeploy: true